---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: loggingauths.rancher.com
  namespace: cattle-system
spec:
  group: rancher.com
  version: v1
  scope: Namespaced
  names:
    plural: loggingauths
    singular: loggingauth
    kind: LoggingAuth
    shortNames:
    - la
---
apiVersion: "rancher.com/v1"
kind: LoggingAuth
metadata:
  name: rancherloggingauth
  namespace: cattle-system
enableNamespaceLogging: false
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: loggings.rancher.com
  namespace: cattle-system
spec:
  group: rancher.com
  version: v1
  scope: Namespaced
  names:
    plural: loggings
    singular: logging
    kind: Logging
    shortNames:
    - lg
