---
kind: Secret
apiVersion: v1
metadata:
  name: loggingsecret
  namespace: default
data:
  loggingsecret: eyJ0eXBlIjoiIiwibGFiZWwiOiIiLCJkYXRhIjp7InVzZXIiOiIiLCJwYXNzd29yZCI6IiIsInRva2VuIjoiIn19
---
kind: Secret
apiVersion: v1
metadata:
  name: loggingsecret
  namespace: cattle-system
data:
  loggingsecret: eyJ0eXBlIjoiIiwibGFiZWwiOiIiLCJkYXRhIjp7InVzZXIiOiIiLCJwYXNzd29yZCI6IiIsInRva2VuIjoiIn19
