---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka
  namespace: kafka
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kafka
subjects:
  - kind: ServiceAccount
    name: kafka
    namespace: kafka
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-web-console
  namespace: kafka
spec:
  type: NodePort
  ports:
  - port: 9000
    nodePort: 30073
    targetPort: 9000
  selector:
    app: kafka-web-console
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kafka-web-console
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-web-console
  template:
    metadata:
      labels:
        app: kafka-web-console
    spec:
      containers:
      - name: kafka-web-console
        image: hwestphal/kafka-web-console
      serviceAccountName: kafka