apiVersion: v1
kind: Service
metadata:
  labels:
    name: httpd
    role: service
  name: httpd
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30062
  type: NodePort
  selector:
    k8s-app: httpd
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myhttpd
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: httpd
  template:
    metadata:
      labels:
        k8s-app: httpd
    spec:
      containers:
      - name: httpd
        image: reg.cnrancher.com/logging/myhttpd:v0.1
        env:
        volumeMounts:
        - name: accesslog
          mountPath: /var/logs/apache
      volumes:
      - name: accesslog
        hostPath:
          path: /var/log/volumes/default/mystack/myservice/apache2

