apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: loggings.rancher.com
  namespace: cattle-system
spec:
  group: rancher.com
  version: v1
  scope: Namespaced
  names:
    plural: loggings
    singular: logging
    kind: Logging
    shortNames:
    - lg
---
apiVersion: "rancher.com/v1"
kind: Logging
metadata:
  name: b84nlkv2nr8ogbkrltl0
  namespace: cattle-system
target:
  # common config
  enable: "true"
  # common config: target type list are: embedded, elasticsearch, splunk, kafka, you could use one of them.
  target_type: elasticsearch
  # common config: you could change key and value to the the tag you want to add to each record, it you don't want to add tag, just delete these three line
  output_records:
    mykey4: mykey4
    mykey3: mykey3
  # common config: for the interval will flush to the remote target
  output_flush_interval: 1
  # elasticsearch config: host, you need to change to your own host, if you use embedded, please change to elasticsearch.cattle-system
  es_host: aliyun_ip
  # elasticsearch config: port, if you use embedded, please change to 9200
  es_port: 30022
  # elasticsearch config
  es_logstash_dateformat: '%Y.%m.%d'
  # elasticsearch config, could you change to the index prefix you want
  es_logstash_prefix: cattle-system
  # splunk config: host
  splunk_host: ""
  # splunk config: the hec port
  splunk_port: 8088
  # splunk config: http or https, base on your splunk
  splunk_protocol: ""
  # splunk config: you could add source type as a filter condition
  splunk_sourcetype: ""
  # splunk config: "none", "unixtime", "localtime"
  splunk_time_format: ""
  # kafka config: use "broker" or "zookeeper", if you choose the broker, please fill in the field kafka_brokers, if you choose the zookeeper, please fill in the field kafka_zookeeper
  kafka_broker_type: broker
  # kafka config: broker list
  kafka_brokers: broker1:port,broker2:port
  # kafka config: zookeeper host and port
  kafka_zookeeper: zookeeper1:port
  kafka_output_data_type: json
  kafka_max_send_retries: 3
  # kafka config: kafka topic
  kafka_default_topic: message
---
apiVersion: "rancher.com/v1"
kind: Logging
metadata:
  name: second
  namespace: default
target:
  enable: "true"
  es_host: aliyun_ip
  es_include_tag_key: true
  es_logstash_dateformat: '%Y.%m.%d'
  es_logstash_format: false
  es_logstash_prefix: default
  es_port: 30022
  output_flush_interval: 1
  output_records:
    mykey2: mykey2
    mykey1: mykey1
  splunk_host: ""
  splunk_port: 0
  splunk_protocol: ""
  splunk_source: ""
  splunk_sourcetype: ""
  splunk_time_format: ""
  target_type: kafka
  kafka_broker_type: broker
  kafka_zookeeper: zookeeper1:port,zookeeper2:port
  kafka_output_data_type: json
  kafka_max_send_retries: 3
  kafka_brokers: broker1:port,broker2:port
  kafka_default_topic: message