apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: loggings.rancher.com
  namespace: cattle-system
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: rancher.com
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: loggings
    # singular name to be used as an alias on the CLI and for display
    singular: logging
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Logging
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - lg
---
apiVersion: "rancher.com/v1"
kind: Logging
metadata:
  name: b84nlkv2nr8ogbkrltl0
  namespace: cattle-system
  enable: "true"
target:
  enable: "true"
  es_host: aliyun_ip
  es_include_tag_key: true
  es_logstash_dateformat: '%Y.%m.%d'
  es_logstash_format: false
  es_logstash_prefix: cattle-system
  es_port: 30022
  output_flush_interval: 1
  output_records:
    mykey4: mykey4
    mykey3: mykey3
  splunk_host: ""
  splunk_port: 0
  splunk_protocol: ""
  splunk_source: ""
  splunk_sourcetype: ""
  splunk_time_format: ""
  target_type: embedded
---
apiVersion: "rancher.com/v1"
kind: Logging
metadata:
  name: second
  namespace: default
  enable: "true"
target:
  enable: "true"
  es_host: aliyun_ip
  es_include_tag_key: true
  es_logstash_dateformat: '%Y.%m.%d'
  es_logstash_format: false
  es_logstash_prefix: default
  es_port: 30022
  output_flush_interval: 1
  output_records:
    mykey2: mykey2
    mykey1: mykey1
  splunk_host: ""
  splunk_port: 0
  splunk_protocol: ""
  splunk_source: ""
  splunk_sourcetype: ""
  splunk_time_format: ""
  target_type: kafka
  kafka_broker_type: broker
  kafka_zookeeper: zookeeper1:port,zookeeper2:port
  kafka_output_data_type: json
  kafka_max_send_retries: 3
  kafka_brokers: broker1:port,broker2:port
  kafka_default_topic: message