apiVersion: "rancher.com/v1"
kind: Logging
metadata:
  name: rancherlogging
  namespace: cattle-system
spec:
  provider: "fluentd"
  latest_version: "1237"
  sources:
  - name: "stack_service"
    environment: default
    input_path: /fluentd/etc/my.log
    input_format: apache2
  targets: 
  - environment: default
    output_type: elasticsearch
    output_host: 192.168.33.176
    output_port: 9200
    output_logstash_prefix: "logstash"
    output_logstash_dateformat: '%Y-%m-%d %H:%M:%S'
    output_tag_key: "mytag3"
status:
  