apiVersion: v1
kind: Service
metadata:
  labels:
    name: mynginx2
    role: service
  name: mynginx2
spec:
  ports:
    - port: 30004
      targetPort: 80
      nodePort: 30003
  type: NodePort
  selector:
    k8s-app: mynginx2
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mydep
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mynginx2
  template:
    metadata:
      labels:
        k8s-app: mynginx2
    spec:
      containers:
      - name: mynginx2
        image: nginx
